Update Setting-Management.md
Added 'ITransientDependency' interface to CustomSettingProvider class, so the following exception will not be thrown:
ComponentNotRegisteredException: The requested service 'CustomSettingProvider' has not been registered.